// eslint-disable-next-line
const crmData = {
  quickStatsData: {
    clientsData: {
      count: '100,000',
    },
    invoiceData: {
      count: '₩ 2,100,600,200',
    },
    totalProjectsData: {
      count: '120,100',
    },
    openProjectsData: {
      count: '14,281',
    },
  },

  statisticsGraph: {
    projectData: [
      {month: '1월', number: 110},
      {month: '2월', number: 280},
      {month: '3월', number: 120},
      {month: '4월', number: 290},
      {month: '5월', number: 140},
      {month: '6월', number: 320},
      {month: '7월', number: 240},
      {month: '8월', number: 400},
      {month: '9월', number: 270},
      {month: '10월', number: 450},
      {month: '11월', number: 280},
      {month: '12월', number: 430},
    ],
    clientsData: [
      {month: '1월', number: 20},
      {month: '2월', number: 170},
      {month: '3월', number: 40},
      {month: '4월', number: 200},
      {month: '5월', number: 70},
      {month: '6월', number: 270},
      {month: '7월', number: 100},
      {month: '8월', number: 310},
      {month: '9월', number: 130},
      {month: '10월', number: 350},
      {month: '11월', number: 170},
      {month: '12월', number: 400},
    ],
    incomeData: [
      {month: '1월', number: 110},
      {month: '2월', number: 230},
      {month: '3월', number: 100},
      {month: '4월', number: 290},
      {month: '5월', number: 160},
      {month: '6월', number: 320},
      {month: '7월', number: 220},
      {month: '8월', number: 450},
      {month: '9월', number: 260},
      {month: '10월', number: 490},
      {month: '11월', number: 240},
      {month: '12월', number: 400},
    ],
  },
  ticketSupportData: [
    {
      id: 1,
      name: '최민경',
      _email: 'rolivie1@kickstarter.com',
      created: '23 Jan, 2019',
      contact: '010-000-0000',
      image: '/assets/images/avatar/A1.jpg',
    },
    {
      id: 2,
      name: '김서현',
      _email: 'mlafranconi2@soundcloud.com',
      created: '12 Jan, 2019',
      contact: '010-000-0000',
      image: '/assets/images/avatar/A2.jpg',
    },
    {
      id: 3,
      name: '김혜지',
      _email: 'dcormode3@w3.org',
      created: '28 Feb, 2019',
      contact: '010-000-0000',
      image: '/assets/images/avatar/A3.jpg',
    },
    {
      id: 4,
      name: '이희대',
      _email: 'ndarwin4@nationalgeographic.com',
      created: '21 Mar, 2019',
      contact: '010-000-0000',
      image: '/assets/images/avatar/A4.jpg',
    },
  ],
  todayTaskData: [
    {
      id: 1,
      task: 'Send the Billing Agreement',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 2,
      task: 'Send over all the documentation',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 3,
      task: 'Call Adam to review the documentation',
      date: '24 Mar, 2019',
      isChecked: true,
    },
    {
      id: 4,
      task: 'Meeting with Daron to review the intake form',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 5,
      task: 'Call Matthew to schedule an interview',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 6,
      task: 'checking UiKings CremaThemeProvider and give customer support',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 7,
      task: 'go to market to buy baby corn',
      date: '24 Mar, 2019',
      isChecked: false,
    },
    {
      id: 8,
      task: 'schedule a meeting with team alpha',
      date: '24 Mar, 2019',
      isChecked: false,
    },
  ],
  websiteTrafficData: [
    {month: '1월', users: 1000},
    {month: '2월', users: 600},
    {month: '3월', users: 1100},
    {month: '4월', users: 900},
    {month: '5월', users: 1000},
    {month: '6월', users: 500},
    {month: '7월', users: 900},
    {month: '8월', users: 800},
    {month: '9월', users: 900},
    {month: '10월', users: 750},
    {month: '11월', users: 700},
    {month: '12월', users: 900},
  ],
};
export default crmData;
