import {UserListObj} from '../../../../../types/models/apps/UserList';
const userList: UserListObj[] = [
  {
    id: 1,
    name: '최민경',
    email: 'jubin.chawla@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A1.jpg',
    label: 312,
  },
  {
    id: 2,
    name: '김서현',
    email: 'mark.johnson@abc.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A2.jpg',
    label: 313,
  },
  {
    id: 3,
    name: '김혜지',
    email: 'shane.lee@mnz.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A3.jpg',
    label: 314,
  },
  {
    id: 4,
    name: '이희대',
    email: 'chris.crains@cde.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A4.jpg',
    label: 315,
  },
  {
    id: 5,
    name: '김철수',
    email: 'jonathan.trott@ewr.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A5.jpg',
    label: 316,
  },
  {
    id: 6,
    name: '한똘똘',
    email: 'rohit.sharma@xcr.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A6.jpg',
    label: 317,
  },
  {
    id: 7,
    name: '박대리',
    email: 'mark.lee@cdf.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A7.jpg',
    label: 318,
  },
  {
    id: 8,
    name: '순이',
    email: 'sain.williams@gww.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A8.jpg',
    label: 319,
  },
  {
    id: 9,
    name: '꿀제이',
    email: 'parth.aulins@ddd.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A9.jpg',
    label: 320,
  },
  {
    id: 10,
    name: '김초이',
    email: 'rahul.bose@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A10.jpg',
    label: 321,
  },
  {
    id: 11,
    name: '박현수',
    email: 'rohan.bopanna4@red.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A11.jpg',
    label: 322,
  },
  {
    id: 12,
    name: '김진구',
    email: 'nikit.panwar@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A12.jpg',
    label: 323,
  },
  {
    id: 13,
    name: '이린',
    email: 'vijay.murli@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A13.jpg',
    label: 324,
  },
  {
    id: 14,
    name: '정석',
    email: 'david.boon@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A14.jpg',
    label: 325,
  },
  {
    id: 15,
    name: '천상계',
    email: 'saurabh.shukla@sdd.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A15.jpg',
    label: 326,
  },
];
export default userList;
