import {UserListObj} from '../../../../../types/models/apps/UserList';
const userList: UserListObj[] = [
  {
    id: 1,
    name: '최민경',
    email: 'jubin.chawla@xyz.com',
    contact: '+1-344432739',
    isStarred: false,
    image: '/assets/images/avatar/A1.jpg',
  },
  {
    id: 2,
    name: '김서현',
    email: 'mark.johnson@abc.com',
    contact: '+1-34354234',
    isStarred: false,
    image: '/assets/images/avatar/A2.jpg',
  },
  {
    id: 3,
    name: '김혜지',
    email: 'shane.lee@mnz.com',
    contact: '+1-324563332',
    isStarred: true,
    image: '/assets/images/avatar/A3.jpg',
  },
  {
    id: 4,
    name: '이희대',
    email: 'chris.crains@cde.com',
    contact: '+1-233454323',
    isStarred: false,
    image: '/assets/images/avatar/A4.jpg',
  },
  {
    id: 5,
    name: 'Jonathan Trott',
    email: 'jonathan.trott@ewr.com',
    contact: '+1-324565345',
    isStarred: false,
    image: '/assets/images/avatar/A5.jpg',
  },
  {
    id: 6,
    name: 'Rohit Sharma',
    email: 'rohit.sharma@xcr.com',
    contact: '+1-435424345',
    isStarred: true,
    image: '/assets/images/avatar/A6.jpg',
  },
  {
    id: 7,
    name: 'Mark Lee',
    email: 'mark.lee@cdf.com',
    contact: '+1-989323434',
    isStarred: false,
    image: '/assets/images/avatar/A7.jpg',
  },
  {
    id: 8,
    name: 'Sain Williams',
    email: 'sain.williams@gww.com',
    contact: '+1-349848303',
    isStarred: false,
    image: '/assets/images/avatar/A8.jpg',
  },
  {
    id: 9,
    name: 'Parth Aulins',
    email: 'parth.aulins@ddd.com',
    contact: '+1-4874387443',
    isStarred: false,
    image: '/assets/images/avatar/A9.jpg',
  },
  {
    id: 10,
    name: 'Rahul Bose',
    email: 'rahul.bose@xyz.com',
    contact: '+1-43235454',
    isStarred: false,
    image: '/assets/images/avatar/A10.jpg',
  },
  {
    id: 11,
    name: 'Rohan Bopanna',
    email: 'rohan.bopanna4@red.com',
    contact: '+1-432123345',
    isStarred: true,
    image: '/assets/images/avatar/A11.jpg',
  },
  {
    id: 12,
    name: 'Nikit Panwar',
    email: 'nikit.panwar@xyz.com',
    contact: '+1-542324563',
    isStarred: false,
    image: '/assets/images/avatar/A12.jpg',
  },
  {
    id: 13,
    name: 'Vijay Murli',
    email: 'vijay.murli@xyz.com',
    contact: '+1-435432434',
    isStarred: false,
    image: '/assets/images/avatar/A13.jpg',
  },
  {
    id: 14,
    name: 'David Boon',
    email: 'david.boon@xyz.com',
    contact: '+1-343322323',
    isStarred: false,
    image: '/assets/images/avatar/A14.jpg',
  },
  {
    id: 15,
    name: 'Saurabh Shukla',
    email: 'saurabh.shukla@sdd.com',
    contact: '+1-334354333',
    isStarred: false,
    image: '/assets/images/avatar/A15.jpg',
  },
  {
    id: 16,
    name: 'Nick Taylor',
    email: 'nick.taylor@usa.com',
    contact: '+1-432543345',
    isStarred: true,
    image: '/assets/images/avatar/A16.jpg',
  },
  {
    id: 17,
    name: 'Nikita Suman',
    email: 'nikita.suman@nicks.com',
    contact: '+91-3283828373',
    isStarred: false,
    image: '/assets/images/avatar/A17.jpg',
  },
  {
    id: 18,
    name: 'Laura Lohan',
    email: 'laura.lohan@laura.com',
    contact: '+1-3232323',
    isStarred: false,
    image: '/assets/images/avatar/A18.jpg',
  },
  {
    id: 19,
    name: 'Jennifer John',
    email: 'jennifer.john@abc.com',
    contact: '+1-334354333',
    isStarred: false,
    image: '/assets/images/avatar/A19.jpg',
  },
  {
    id: 20,
    name: 'Robert Key',
    email: 'robert.key@key.com',
    contact: '+1-3289893323',
    isStarred: false,
    image: '/assets/images/avatar/A20.jpg',
  },
];
export default userList;
