import {UserListObj} from '../../../../../types/models/apps/UserList';
const userList: UserListObj[] = [
  {
    id: 1,
    name: '최민경',
    email: 'jubin.chawla@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A1.jpg',
  },
  {
    id: 2,
    name: '김서현',
    email: 'mark.johnson@abc.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A2.jpg',
  },
  {
    id: 3,
    name: '김혜지',
    email: 'shane.lee@mnz.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A3.jpg',
  },
  {
    id: 4,
    name: '이희대',
    email: 'chris.crains@cde.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A4.jpg',
  },
  {
    id: 5,
    name: '김철수',
    email: 'jonathan.trott@ewr.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A5.jpg',
  },
  {
    id: 6,
    name: '한똘똘',
    email: 'rohit.sharma@xcr.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A6.jpg',
  },
  {
    id: 7,
    name: '박대리',
    email: 'mark.lee@cdf.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A7.jpg',
  },
  {
    id: 8,
    name: '순이',
    email: 'sain.williams@gww.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A8.jpg',
  },
  {
    id: 9,
    name: '꿀제이',
    email: 'parth.aulins@ddd.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A9.jpg',
  },
  {
    id: 10,
    name: '김초이',
    email: 'rahul.bose@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A10.jpg',
  },
  {
    id: 11,
    name: '박현수',
    email: 'rohan.bopanna4@red.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A11.jpg',
  },
  {
    id: 12,
    name: '김진구',
    email: 'nikit.panwar@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A12.jpg',
  },
  {
    id: 13,
    name: '이린',
    email: 'vijay.murli@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A13.jpg',
  },
  {
    id: 14,
    name: '정석',
    email: 'david.boon@xyz.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A14.jpg',
  },
  {
    id: 15,
    name: '천상계',
    email: 'saurabh.shukla@sdd.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A15.jpg',
  },
  {
    id: 16,
    name: '지상계',
    email: 'nick.taylor@usa.com',
    contact: '010-000-000',
    isStarred: true,
    image: '/assets/images/avatar/A16.jpg',
  },
  {
    id: 17,
    name: '데이비드',
    email: 'nikita.suman@nicks.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A17.jpg',
  },
  {
    id: 18,
    name: '박찬호',
    email: 'laura.lohan@laura.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A18.jpg',
  },
  {
    id: 19,
    name: '김연아',
    email: 'jennifer.john@abc.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A19.jpg',
  },
  {
    id: 20,
    name: '로버트',
    email: 'robert.key@key.com',
    contact: '010-000-000',
    isStarred: false,
    image: '/assets/images/avatar/A20.jpg',
  },
];
export default userList;
